// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCkxbFl2BUKH1GRJ07CsXkqbgKzmLRIX4',
    appId: '1:288237184107:web:18a2b77d8bf28bd205bd2e',
    messagingSenderId: '288237184107',
    projectId: 'gain-quest',
    authDomain: 'gain-quest.firebaseapp.com',
    storageBucket: 'gain-quest.firebasestorage.app',
    measurementId: 'G-RCMRJ9XQS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXzleULbkM9vJoaMkuzJYx9-PExhoTW7k',
    appId: '1:288237184107:android:42e420a950f25f9905bd2e',
    messagingSenderId: '288237184107',
    projectId: 'gain-quest',
    storageBucket: 'gain-quest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQzZeDYFvKKJoDTAqmmlbeejmoed25s7c',
    appId: '1:288237184107:ios:b842b86fc63a6ab105bd2e',
    messagingSenderId: '288237184107',
    projectId: 'gain-quest',
    storageBucket: 'gain-quest.firebasestorage.app',
    iosBundleId: 'com.example.gainQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQzZeDYFvKKJoDTAqmmlbeejmoed25s7c',
    appId: '1:288237184107:ios:b842b86fc63a6ab105bd2e',
    messagingSenderId: '288237184107',
    projectId: 'gain-quest',
    storageBucket: 'gain-quest.firebasestorage.app',
    iosBundleId: 'com.example.gainQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCkxbFl2BUKH1GRJ07CsXkqbgKzmLRIX4',
    appId: '1:288237184107:web:ac63f20ff45302c805bd2e',
    messagingSenderId: '288237184107',
    projectId: 'gain-quest',
    authDomain: 'gain-quest.firebaseapp.com',
    storageBucket: 'gain-quest.firebasestorage.app',
    measurementId: 'G-F9GRGB8B7G',
  );
}
